spring:
  application:
    name: config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dupeihui/config-repo.git
          force-pull: true
#          username:
#          password:
#          search-paths:

server:
  port: 60000
