spring:
  application:
    name: config-bus-server
  rabbitmq:
    host: 192.168.31.58
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dupeihui/config-repo.git
          force-pull: true
#          username:
#          password:
#          search-paths:

server:
  port: 60002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always